twitter:
  debug: true
  oauth:
    consumerKey: epK94MOx6HiAzfDO53wQEtysr
    consumerSecret: yJQwZS3hJYu9kVtuFr5G1oXt1JHZZJNRCeol43N0NPfpZAex70
    accessToken: 1132736931979247616-UGrCbv5tiRvCGewFlM2TrlvQShl1Sd
    accessTokenSecret: IITld7ZyZczAES6gIBgjcno2OWwhLSaqQadklTHTNawDx









