twitter:
  debug: true
  oauth:
    consumerKey: 4c73SQEyvBr7Gv28OUOcSBD2G
    consumerSecret: BypzysnBuu8DXmc6bQU20KX1XE3ZYZo0RMp0qQaDVlgcQtT0KV
    accessToken: 1132736931979247616-isjGc7Qs2fm01vGOT46KtmypfzgRfc
    accessTokenSecret: ZD6et6g3QO7n3kVFUFkKCvnf9bvYSjanloSX5hqH8p01B









